services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-solutions-front
    restart: unless-stopped
    environment:
      VITE_AUTH_API_URL: ${VITE_AUTH_API_URL:-http://localhost:8081}
      VITE_CORE_API_URL: ${VITE_CORE_API_URL:-http://localhost:8082}
      VITE_PAYMENT_API_URL: ${VITE_PAYMENT_API_URL:-http://localhost:3000}
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
